//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvctest.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://outlook.microsoft.com/add-ins/SMS/wsdl/", ConfigurationName="ServiceReference1.SMSWebServiceSoapPort")]
    public interface SMSWebServiceSoapPort {
        
        // CODEGEN: 消息 sendXmlRequest 的包装命名空间(http://outlook.microsoft.com/add-ins/SMS/message/)以后生成的消息协定与默认值(http://outlook.microsoft.com/add-ins/SMS/wsdl/)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="http://outlook.microsoft.com/add-ins/SMS/action/SMSWebService.sendXml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        mvctest.ServiceReference1.sendXmlResponse sendXml(mvctest.ServiceReference1.sendXmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://outlook.microsoft.com/add-ins/SMS/action/SMSWebService.sendXml", ReplyAction="*")]
        System.Threading.Tasks.Task<mvctest.ServiceReference1.sendXmlResponse> sendXmlAsync(mvctest.ServiceReference1.sendXmlRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendXml", WrapperNamespace="http://outlook.microsoft.com/add-ins/SMS/message/", IsWrapped=true)]
    public partial class sendXmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Carrier;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string ToMobile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string Message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string MsgType;
        
        public sendXmlRequest() {
        }
        
        public sendXmlRequest(string Carrier, string Id, string Password, string ToMobile, string Message, string MsgType) {
            this.Carrier = Carrier;
            this.Id = Id;
            this.Password = Password;
            this.ToMobile = ToMobile;
            this.Message = Message;
            this.MsgType = MsgType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendXmlResponse", WrapperNamespace="http://outlook.microsoft.com/add-ins/SMS/message/", IsWrapped=true)]
    public partial class sendXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        public sendXmlResponse() {
        }
        
        public sendXmlResponse(string Result) {
            this.Result = Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SMSWebServiceSoapPortChannel : mvctest.ServiceReference1.SMSWebServiceSoapPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMSWebServiceSoapPortClient : System.ServiceModel.ClientBase<mvctest.ServiceReference1.SMSWebServiceSoapPort>, mvctest.ServiceReference1.SMSWebServiceSoapPort {
        
        public SMSWebServiceSoapPortClient() {
        }
        
        public SMSWebServiceSoapPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMSWebServiceSoapPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSWebServiceSoapPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSWebServiceSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        mvctest.ServiceReference1.sendXmlResponse mvctest.ServiceReference1.SMSWebServiceSoapPort.sendXml(mvctest.ServiceReference1.sendXmlRequest request) {
            return base.Channel.sendXml(request);
        }
        
        public string sendXml(string Carrier, string Id, string Password, string ToMobile, string Message, string MsgType) {
            mvctest.ServiceReference1.sendXmlRequest inValue = new mvctest.ServiceReference1.sendXmlRequest();
            inValue.Carrier = Carrier;
            inValue.Id = Id;
            inValue.Password = Password;
            inValue.ToMobile = ToMobile;
            inValue.Message = Message;
            inValue.MsgType = MsgType;
            mvctest.ServiceReference1.sendXmlResponse retVal = ((mvctest.ServiceReference1.SMSWebServiceSoapPort)(this)).sendXml(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<mvctest.ServiceReference1.sendXmlResponse> mvctest.ServiceReference1.SMSWebServiceSoapPort.sendXmlAsync(mvctest.ServiceReference1.sendXmlRequest request) {
            return base.Channel.sendXmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<mvctest.ServiceReference1.sendXmlResponse> sendXmlAsync(string Carrier, string Id, string Password, string ToMobile, string Message, string MsgType) {
            mvctest.ServiceReference1.sendXmlRequest inValue = new mvctest.ServiceReference1.sendXmlRequest();
            inValue.Carrier = Carrier;
            inValue.Id = Id;
            inValue.Password = Password;
            inValue.ToMobile = ToMobile;
            inValue.Message = Message;
            inValue.MsgType = MsgType;
            return ((mvctest.ServiceReference1.SMSWebServiceSoapPort)(this)).sendXmlAsync(inValue);
        }
    }
}
